name: Build and Upload

on:
  workflow_call:

permissions:
  contents: write
  packages: write

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - uses: open-policy-agent/setup-opa@v2
        with:
          version: 1.6.0
      - run: mkdir -p dist && opa build -b policies -o dist/bundle.tar.gz
      - uses: softprops/action-gh-release@v2
        with:
          files: dist/bundle.tar.gz
      - run: go install github.com/compliance-framework/gooci@latest
      - run: gooci login ghcr.io --username "${{ github.actor }}" --password "${{ secrets.GITHUB_TOKEN }}"
      - run: gooci upload-single dist/bundle.tar.gz "ghcr.io/${{ github.repository }}:${{ github.ref_name }}"
      - if: ${{ !github.event.release.prerelease }}
        run: gooci upload-single dist/bundle.tar.gz "ghcr.io/${{ github.repository }}:latest"
